# Spot instances
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: roboshop
    region: us-east-1

managedNodeGroups:
   - name: Spot
     instanceTypes: ["t3.medium","c4.large","c5.large","c5d.large","c5n.large","c5a.large"]
     spot: true
     desiredCapacity: 2
   